apiVersion: apps/v1
kind: Deployment
metadata:
  name: tindibandi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tindibandi-app
  template:
    metadata:
      labels:
        app: tindibandi-app
    spec:
      containers:
      - name: tindibandi-app
        image: manideep2003/capsuleproject-updated-app:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/tindibandi"
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          value: "production"
        - name: JWT_SECRET
          value: "your-jwt-secret-key"
        - name: ADMIN_PASSWORD
          value: "admin123"
        - name: SESSION_SECRET
          value: "your-session-secret"
---
apiVersion: v1
kind: Service
metadata:
  name: tindibandi-service
spec:
  selector:
    app: tindibandi-app
  ports:
  - port: 80
    targetPort: 3001
  type: LoadBalancer
